language: node_js

os: osx

osx_image: xcode10.1

node_js:
  - 10

before_script:
  - nightwatch --version
  - java -version
  - sleep 3
  - safaridriver --enable

script:
  - make test

dist: trusty

sudo: required
