language: node_js

node_js:
  - 10

before_script:
  - nightwatch --version
  - java -version
  - google-chrome --version

script:
  - make test

dist: xenial

services:
  - xvfb

sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
