name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: npm install
        run: |
          npm install
      - name: npm test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
